### ISSUE TITLE
Publish docs under Github Pages

### ISSUE THREAD

**Issue by niutech** [mingodad/ljs#1]
Docs are in HTML format, so please go to the repository Settings and enable serving GitHub Pages from the `/docs` folder:

![github pages](https://user-images.githubusercontent.com/384997/50552716-86a4fd00-0c99-11e9-9839-a2869776a1d2.png)

Thanks!

**Comment by mingodad** [comment]
Hello !
Thanks for your advice, but that option is not enabled I can't select it.
It's not clear why it's not available.

**Comment by niutech** [comment]
Maybe because you have to rename `/doc`  folder to `/docs`?

**Comment by phorward** [comment]
You can use and link to raw.githack.com mirrored links to serve the repository's HTML content, look here:

- https://raw.githack.com/mingodad/ljs/master/doc/readme.html
- https://raw.githack.com/mingodad/ljs/master/doc/manual.html
- https://raw.githack.com/mingodad/ljs/master/doc/contents.html

**Comment by mingodad** [comment]
Thank you for pointing out this, looking through that links I can see that I need to revise again that documentation as I found several omissions, errors introduced by me.
