### ISSUE TITLE
lopcodes change error

### ISSUE THREAD

**Issue by mudebug77** [mingodad/ljs#12]
i want to modify change
OP_MOVE
OP_LOADK
order, prevent hackers (Luadec)

code:

local CallCount = 0;
function Test2()
{
if (CallCount > 10)  //error Always True
{
print("Compare_:"..CallCount);
}else
{
print("Count:"..CallCount);
}
CallCount++;
}

Occurs (CallCount > 10) equals TRUE

**Comment by mingodad** [comment]
I'm testing this and it seems to work as expected:
```
local CallCount = 0;
function Test2()
{
	if (CallCount > 10) //error Always True
	{
		print("Compare_:"..CallCount);
	} else {
		print("Count:"..CallCount);
	}
	CallCount++;
}

for(i=1,12) Test2();
```
Output:
```
ljs "test-comparison.ljs"
Count:0
Count:1
Count:2
Count:3
Count:4
Count:5
Count:6
Count:7
Count:8
Count:9
Count:10
Compare_:11
```
Can you provide a fully working example and the output you are getting ?

```

**Comment by mudebug77** [comment]
I have figured out why I did it wrong.
Thank you

Hope to modify for
Example: for(local i=0;i<10;i+=1)
