### ISSUE TITLE
IF and format error

### ISSUE THREAD

**Issue by mudebug77** [mingodad/ljs#13]
lua.set_function("TestNumber", [=]()->lua_Number {return (lua_Number)0; });

code:
function Test()
{
	local ss = TestNumber();  //《===    ss = 0
	if (ss)
	{

		print(string.format("A-number:0x%08X",ss));   //《=== Enter ???????????
	}else
	{
		print(string.format("B-number:0x%08X",ss));
	}
}
Test()

**Comment by mingodad** [comment]
LJS does not modify the interpretation of booleans, it behaves like Lua:
```
function TestNumber() return 0; end

function Test()
	local ss = TestNumber(); --《=== ss = 0
	if ss then
		print(string.format("A-number:0x%08X",ss));   --《=== Enter ???????????
	else
		print(string.format("B-number:0x%08X",ss));
	end
end
Test()
```
