### ISSUE TITLE
Where are annotations in the source code.

### ISSUE THREAD

**Issue by AsynchronousAI** [mingodad/ljs#14]
Hello, I am making some personal modifications to ljs, I am looking for the code snippet where you added variable annotations but cannot find it. Could you tell me which C file it would be in?

**Comment by mingodad** [comment]
It's here https://github.com/mingodad/ljs/blob/eb6fe95de71f71cf8790209eec1f1e494d97dcdf/src/lparser.c#L834

**Comment by AsynchronousAI** [comment]
Thanks.
